name: Checkout Test

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: branch-3.0
        run: echo "${{ github.event.base_ref }}"
