name: Checkout Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: tree .
      - uses: actions/checkout@v3
        with:
          path: a
      - run: tree .
      - uses: actions/checkout@v3
        with:
          path: b
      - run: tree .
